/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'tm1c14' at '02/08/16 14:47' with Gradle 2.4
 *
 * @author tm1c14, @date 02/08/16 14:47
 */
public class Library {
    public boolean someLibraryMethod() {
		System.out.println("Hello world");
        return true;
    }
}
